name: PoliticalAlignmentCaseStudy

dependencies:
  - python
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - statsmodels
  - pytables
  - pip
  - pip:
    - statadict
    - empiricaldist
